### ISSUE TITLE
Error Crashed

### ISSUE THREAD

**Issue by ryzam** [rogeralsing/Microphone#19] opened 2015-11-07 12:26 UTC
I tried to make 100000 requests call to WebApi that has been registered in Consul cluster for 2 instances that running in the same local machine. The server return successful response but suddenly in the middle of the request I received Error Crashed exception "Unable to connect to remote server"

**Comment by rogeralsing** [comment] 2015-11-07 12:36
It seems like the Consul agent for some reason wasn't able to process the request for service status.
That is the only place that logs an exception with the text "crashed" (`Logger.Error(x, "Crashed");`) 

This in itself is not critical as this only delays the removal of any potentially dead services.

Is the problem reproducible or was it a one time event?

**Comment by ryzam** [comment] 2015-11-07 12:45
It's not one time event, happen when reached  > 30K call requests. 
I have changed the client code to make a direct call  to the WebAPI for a testing and has no problem at all.

**Comment by ryzam** [comment] 2015-11-08 06:16
Here is the detail execption message
"An operation on a socket could not be performed because the system lack sufficient buffer space or because a queue was full"

**Comment by rogeralsing** [comment] 2015-11-08 08:44
http://stackoverflow.com/questions/4415175/an-operation-on-a-socket-could-not-be-performed-because-the-system-lacked-suffi

Seems like a resource leak in the `ConsulRestClient`. the `HttpClient` needs proper disposing.

**Comment by ryzam** [comment] 2015-11-08 11:11
I have change the code in ConsulRestClient

try
            {
                using (HttpClient client = new HttpClient())
                {
                    var response = await client.GetAsync(string.Format("http://localhost:{0}/v1/health/state/critical", consulPort)).ConfigureAwait(true);
....
}
catch{...}

**Comment by rogeralsing** [comment] 2016-04-02 18:58
This have been resolved earlier, closing

**Closed by rogeralsing** 2016-04-02 18:58 UTC
Labels: bug
